name: dotted_line_flutter
description: This package allows you to draw dotted lines with Flutter. You can draw a beautiful dotted line.
version: 0.1.2
homepage: https://github.com/Puneetsharma5525/dotted_line_flutter
repository: https://github.com/Puneetsharma5525/dotted_line_flutter
environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        package: com.example.untitled
        pluginClass: UntitledPlugin
      ios:
        pluginClass: UntitledPlugin
      linux:
        pluginClass: UntitledPlugin
      macos:
        pluginClass: UntitledPlugin
      windows:
        pluginClass: UntitledPluginCApi
      web:
        pluginClass: UntitledWeb
        fileName: untitled_web.dart